# Generated by Django 3.2.6 on 2021-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes_taken',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(choices=[('pacific', 'Pacific Time (PT)'), ('mountain', 'Mountain Time (MT)'), ('central', 'Central Time (CT)'), ('eastern', 'Eastern Time (ET)')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='times_available',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/images/profile_pics/default_pic.png', upload_to='images/profile_pics'),
        ),
        migrations.DeleteModel(
            name='Tutor_Info',
        ),
    ]
