# Generated by Django 3.2.6 on 2021-10-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211011_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
    ]
