# Generated by Django 3.2.6 on 2021-10-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_school_name_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='average_rating',
            new_name='tutee_avg_rating',
        ),
        migrations.AddField(
            model_name='user',
            name='tutor_avg_rating',
            field=models.FloatField(null=True),
        ),
    ]
