# Generated by Django 3.2.6 on 2021-10-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211015_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classes_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, choices=[('pacific', 'Pacific Time (PT)'), ('mountain', 'Mountain Time (MT)'), ('central', 'Central Time (CT)'), ('eastern', 'Eastern Time (ET)')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='times_available',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tutee_avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tutor_avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
