# Generated by Django 3.2.6 on 2021-11-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211024_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('purchase', 'PURCHASE'), ('transfer', 'TRANSFER'), ('cash_out', 'CASH_OUT')], max_length=25),
        ),
    ]
