# Generated by Django 3.2.6 on 2021-11-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211104_0104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tutor_request',
            new_name='TutorRequest',
        ),
    ]
