# Generated by Django 3.2.6 on 2021-11-04 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_tutor_request_tutorrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='type',
            new_name='rating_type',
        ),
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='date_requested',
            new_name='date_request_sent',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='tutee_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='tutor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
