# Generated by Django 3.2.6 on 2021-11-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211104_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='date_request_sent',
            new_name='date_sent_request',
        ),
    ]
