# Generated by Django 3.2.6 on 2021-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_date_request_sent_tutorrequest_date_sent_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='time',
            new_name='tutor_start_time',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='date',
        ),
        migrations.AddField(
            model_name='rating',
            name='date_rating_given',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_transaction_made',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='date_sent_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
