# Generated by Django 3.2.7 on 2021-11-14 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211107_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='tutor_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
