# Generated by Django 3.2.7 on 2021-11-17 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='tutor_time',
            new_name='tutor_end_time',
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='tutor_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
