# Generated by Django 3.2.9 on 2021-11-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211116_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='tutee_completed',
            field=models.BooleanField(default=False),
        ),
    ]
